apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
  annotations:
    k8s-confsec-reloader.io/watch: "true"
    k8s-confsec-reloader.io/keys-to-watch: "DB_PASSWORD,API_SECRET"
    k8s-confsec-reloader.io/do-nothng: "nothing_to_do"
type: Opaque
data:
  DB_PASSWORD: "aTNUa1JibDBGc2hpdEhybzJlaDhBdw==" # base64 encoded "password123"
  API_SECRET: "c3VwZXItc2VjcmV0LWtleQ==" # base64 encoded "super-secret-key"
  UNUSED_SECRET: "dXNlbGVzcw==" # base64 encoded "useless"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-secret
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-secret
  template:
    metadata:
      labels:
        app: test-app-secret
    spec:
      containers:
        - name: test-container
          image: nginx
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_PASSWORD
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: API_SECRET
          envFrom:
            - secretRef:
                name: my-secret
